### ISSUE TITLE
Installation of siegfried fails in CI/CD

### ISSUE THREAD

**Issue by jnik-aarhus** [aarhusstadsarkiv/digiarch#171]
Perhaps we need sudo apt update before all these:
```yaml
      - run:
          name: "Install sf (siegfried)"
          command: |
            wget -qO - https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -
            echo "deb http://dl.bintray.com/siegfried/debian wheezy main" | sudo tee -a /etc/apt/sources.list
            sudo apt update && sudo apt install siegfried
```
